export const fieldHeadData = [
  { id: "project", label: "Project" },
  { id: "contractor", label: "Contractor" },
  { id: "startDate", label: "Start Date" },
  { id: "requestDate", label: "Request Date" },
  { id: "requestBy", label: "Request By" },
  { id: "comments", label: "Comments" },
  { id: "actions", label: "Actions" },
];

export const fieldCellData = [
  {
    id: 1,
    project: "NH Station",
    contractor: "ACME Construction LTD",
    startDate: "2025-04-15",
    requestDate: "2025-04-15",
    requestBy: "Charles Duncan",
    comments: "",
  },
  {
    id: 2,
    project: "Clear to Yard",
    contractor: "Adams Construction LLC",
    startDate: "2025-04-16",
    requestDate: "2025-04-16",
    requestBy: "Charles Duncan",
    comments: "",
  },
  {
    id: 3,
    project: "Fab Bowling",
    contractor: "ABC Concrete",
    startDate: "2025-04-24",
    requestDate: "2025-04-24",
    requestBy: "Harry Williams",
    comments: "",
  },
  {
    id: 4,
    project: "Centennial Pool",
    contractor: "Jones Bros Concrete",
    startDate: "2025-04-28",
    requestDate: "2025-04-28",
    requestBy: "Harry Williams",
    comments: "Report to John W",
  },
  {
    id: 5,
    project: "Clear to Yard",
    contractor: "Altitude Construction",
    startDate: "2025-05-04",
    requestDate: "2025-05-04",
    requestBy: "Charles Duncan",
    comments: "",
  },
  {
    id: 6,
    project: "Railroad Museum",
    contractor: "Smith Construction LTD",
    startDate: "2025-05-09",
    requestDate: "2025-05-09",
    requestBy: "Harry Williams",
    comments: "",
  },
  {
    id: 7,
    project: "StVrain School",
    contractor: "Jones Concrete",
    startDate: "2025-05-16",
    requestDate: "2025-05-16",
    requestBy: "Larry Neville",
    comments: "Request Apprentice",
  },
  {
    id: 8,
    project: "HQ Office",
    contractor: "Blue River Construction",
    startDate: "2025-05-19",
    requestDate: "2025-05-19",
    requestBy: "Charles Duncan",
    comments: "",
  },
  {
    id: 9,
    project: "Clear to Yard",
    contractor: "Jones Bros Concrete",
    startDate: "2025-06-15",
    requestDate: "2025-06-15",
    requestBy: "Harry Williams",
    comments: "",
  },
  {
    id: 10,
    project: "Clear to Yard",
    contractor: "Evergreen Construction",
    startDate: "2025-06-30",
    requestDate: "2025-06-30",
    requestBy: "Larry Neville",
    comments: "Report to Steve",
  },
  {
    id: 11,
    project: "Sunset Pool",
    contractor: "ABC Concrete",
    startDate: "2025-07-15",
    requestDate: "2025-07-15",
    requestBy: "Larry Neville",
    comments: "",
  },
];
